// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFlHYDrSwR6WvPO8FLfQK_vDXDhNkmu6w',
    appId: '1:817090883427:web:8a453f88ef8c2c17ffad56',
    messagingSenderId: '817090883427',
    projectId: 'insurance-company-1',
    authDomain: 'insurance-company-1.firebaseapp.com',
    storageBucket: 'insurance-company-1.firebasestorage.app',
    measurementId: 'G-K2WY15286R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDu_eq62WtF7YcK56NWyJ4VTkKmuhdsMw',
    appId: '1:817090883427:android:983caf52c0dd850affad56',
    messagingSenderId: '817090883427',
    projectId: 'insurance-company-1',
    storageBucket: 'insurance-company-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXBjamhMgl4wVlYUvtIZP0mbVL1H2i5sc',
    appId: '1:817090883427:ios:5d96e701904ba5afffad56',
    messagingSenderId: '817090883427',
    projectId: 'insurance-company-1',
    storageBucket: 'insurance-company-1.firebasestorage.app',
    iosBundleId: 'com.example.insuranceCompany',
  );
}